In [1]:
import numpy as np 
import pandas as pd 

In [3]:
df = pd.read_csv(r"C:\Users\shray\Desktop\datasets\emails.csv")

In [4]:
df

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
0       0       0    0               0         0         0   0    0   
1       0       0    0               0         0         0   1    0   
2       0       0    0               0         0         0   0    0   
3       0       0    0               0         0         0   0    0   
4       0       0    0               0         0         0   1    0   
...   ...     ...  ...             ...       ...       ...  ..  ...   
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
0              0  
1              0  
2              0  
3              0  
4              0  
...          ...  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5172 rows x 3002 columns]

In [5]:
df.isna().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [7]:
x=df.drop(['Email No.','Prediction'],axis=1)
y=df['Prediction']

In [9]:
from sklearn.model_selection import train_test_split

# Split the data into 80% train and 20% test
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize the KNN classifier with k=5 (you can experiment with different values of k)
knn = KNeighborsClassifier(n_neighbors=5)

# Train the KNN model
knn.fit(X_train, y_train)

# Make predictions on the test set
y_pred_knn = knn.predict(X_test)

# Evaluate the KNN model
print("KNN Model Accuracy: ", accuracy_score(y_test, y_pred_knn))
print("KNN Classification Report: \n", classification_report(y_test, y_pred_knn))
print("KNN Confusion Matrix: \n", confusion_matrix(y_test, y_pred_knn))


KNN Model Accuracy:  0.8628019323671497
KNN Classification Report: 
               precision    recall  f1-score   support

           0       0.93      0.87      0.90       739
           1       0.73      0.84      0.78       296

    accuracy                           0.86      1035
   macro avg       0.83      0.86      0.84      1035
weighted avg       0.87      0.86      0.87      1035

KNN Confusion Matrix: 
 [[645  94]
 [ 48 248]]


In [11]:
from sklearn.svm import SVC

# Initialize the SVM classifier
svm = SVC(kernel='linear')  # You can experiment with different kernels

# Train the SVM model
svm.fit(X_train, y_train)

# Make predictions on the test set
y_pred_svm = svm.predict(X_test)

# Evaluate the SVM model
print("SVM Model Accuracy: ", accuracy_score(y_test, y_pred_svm))
print("SVM Classification Report: \n", classification_report(y_test, y_pred_svm))
print("SVM Confusion Matrix: \n", confusion_matrix(y_test, y_pred_svm))


SVM Model Accuracy:  0.9594202898550724
SVM Classification Report: 
               precision    recall  f1-score   support

           0       0.98      0.97      0.97       739
           1       0.92      0.94      0.93       296

    accuracy                           0.96      1035
   macro avg       0.95      0.95      0.95      1035
weighted avg       0.96      0.96      0.96      1035

SVM Confusion Matrix: 
 [[715  24]
 [ 18 278]]


In [12]:
# Compare Accuracy
print(f"KNN Accuracy: {accuracy_score(y_test, y_pred_knn)}")
print(f"SVM Accuracy: {accuracy_score(y_test, y_pred_svm)}")

# Compare Classification Reports
print("KNN Classification Report: \n", classification_report(y_test, y_pred_knn))
print("SVM Classification Report: \n", classification_report(y_test, y_pred_svm))

# Compare Confusion Matrices
print("KNN Confusion Matrix: \n", confusion_matrix(y_test, y_pred_knn))
print("SVM Confusion Matrix: \n", confusion_matrix(y_test, y_pred_svm))


KNN Accuracy: 0.8628019323671497
SVM Accuracy: 0.9594202898550724
KNN Classification Report: 
               precision    recall  f1-score   support

           0       0.93      0.87      0.90       739
           1       0.73      0.84      0.78       296

    accuracy                           0.86      1035
   macro avg       0.83      0.86      0.84      1035
weighted avg       0.87      0.86      0.87      1035

SVM Classification Report: 
               precision    recall  f1-score   support

           0       0.98      0.97      0.97       739
           1       0.92      0.94      0.93       296

    accuracy                           0.96      1035
   macro avg       0.95      0.95      0.95      1035
weighted avg       0.96      0.96      0.96      1035

KNN Confusion Matrix: 
 [[645  94]
 [ 48 248]]
SVM Confusion Matrix: 
 [[715  24]
 [ 18 278]]
